### PR TITLE
A bunch of useful changes

### PR DESCRIPTION
**Pull request by qualk**
refactor ♻️➖: removed iris legacy, local libs
style 🎨: organised imports, build.gradle
fix ➕: use Figura's luaj fork for better compatibility (https://github.com/MCModderAnchor/TACZ/pull/154)
chore 📦️⬆️: updated deps & loom
i10n 🌐: updated translations from https://github.com/MCModderAnchor/TACZ/pull/132
fixed some spelling mistakes like GunMonMixinPlugin -> GunModMixinPlugin

### CODE REVIEW

**Review by LaeDev — CHANGES_REQUESTED** [review]
Good `.gitattributes` and workflows, but please do not edit gradle stuffs and Korean annotation in the future.

**Comment by LaeDev** [comment]
this pull request will be in separate branch in the future and edit it and merge into stable version.

**Comment by qualk** [comment]
> please do not edit gradle stuffs and Korean annotation in the future. 
My apologies. Should I add the Korean annotations back in?

**Comment by LaeDev** [comment]
I'll split the branches and combine them with the main side with my own modifications :)

**Review by LaeDev — APPROVED** [review]

**Pull request merged**
